# netlify.toml

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5174
  publish = "dist"
  autoLaunch = false
  framework = "#custom"
  functionsPort = 8888

[functions]
  node_bundler = "esbuild"
  
[context.production.environment]
  PRINTIFY_API_TOKEN = "YOUR_PRINTIFY_API_TOKEN"
  PRINTIFY_SHOP_ID = "YOUR_PRINTIFY_SHOP_ID"
