# netlify.toml
# Fixed functions path (removed ../ for root execution). Proxy redirect handles query params.

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"  # Changed to correct relative path from root

[dev]
  base = "project"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  functions = "netlify/functions"  # Changed to correct relative path from root

[[redirects]]
  from = "/api/proxy-image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"