# netlify.toml

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"  # Correct path from project base

[dev]
  base = "project"
  command = "npm run dev"
  targetPort = 3000  # Vite is running on 3000
  port = 3002
  publish = "dist"
  functions = "../netlify/functions"  # Correct path from project base

[[redirects]]
  from = "/api/proxy-image"
  to = "/.netlify/functions/proxy-image"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  PRINTIFY_API_TOKEN = "${PRINTIFY_API_TOKEN}"
  PRINTIFY_SHOP_ID = "${PRINTIFY_SHOP_ID}"
  SUPABASE_URL = "${SUPABASE_URL}"
  SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"

[dev.environment]
  PRINTIFY_API_TOKEN = "${PRINTIFY_API_TOKEN}"
  PRINTIFY_SHOP_ID = "${PRINTIFY_SHOP_ID}"
  SUPABASE_URL = "${SUPABASE_URL}"
  SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"
