# netlify.toml

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"  # Adjust if functions are at root/netlify/functions

[dev]
  base = "project"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/proxy-image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
