# netlify.toml (place this next to package.json in your repo root)

[build]
  # (used only on real deploys)
  command   = "npm --prefix project run build"
  publish   = "project/dist"         # or "project/build" if you’re using CRA
  functions = "netlify/functions"

[dev]
  # when you run `netlify dev`, do this:
  command    = "npm --prefix project run dev"        # your Vite dev command
  targetPort = 5173                  # Vite’s default dev port
  port       = 8888                  # the port you’ll open in the browser
  functions  = "netlify/functions"   # same functions folder

# redirect all URLs to index.html so your SPA routes still work
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
