# netlify.toml

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"  # Correct path from project base

[dev]
  base = "project"
  command = "npm run dev"
  targetPort = 5173  # Vite default port
  port = 8888
  publish = "dist"
  functions = "../netlify/functions"  # Correct path from project base

[[redirects]]
  from = "/api/proxy-image"
  to = "/.netlify/functions/proxy-image"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"