# netlify.toml
# Fixed functions path for base dir and updated Node to 20 for engine compatibility.

[build]
  base = "project"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"  # Points to root/netlify/functions from base "project"

[dev]
  base = "project"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  functions = "../netlify/functions"  # Same for dev

[[redirects]]
  from = "/api/proxy-image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"  # Updated to resolve engine warnings