# netlify.toml

[build]
  command = "cd project && npm run build"
  publish = "project/dist"
  functions = "netlify/functions"

[dev]
  command = "cd project && npm run dev"
  targetPort = 5174
  port = 3000
  publish = "project/dist"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  
[context.production.environment]
  PRINTIFY_API_TOKEN = "YOUR_PRINTIFY_API_TOKEN"
  PRINTIFY_SHOP_ID = "YOUR_PRINTIFY_SHOP_ID"
