[build]
  command   = "npm --prefix project run build"
  publish   = "project/dist"
  functions = "netlify/functions"

[dev]
  command    = "npm --prefix project run dev"
  targetPort = 5173
  port       = 8888
  functions  = "netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
