# netlify.toml
[build]
  # (for your production deploy)
  publish   = "dist"                # or "build" if you're using CRA
  functions = "netlify/functions"  # where your lambdas live

[dev]
  # command Netlify Dev should run to start your front-end
  command    = "npm run dev"
  # the port your front-end dev server listens on
  targetPort = 5173
  # the port Netlify Dev will expose in your browser (you’ll visit this)
  port       = 8888
  # reuse the same functions folder from [build]
  functions  = "netlify/functions"

# optional SPA redirect so routes like /products/123 still work
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
