# ./pyproject.toml  — just a stub so uv is happy
[project]
name = "codex-placeholder"
version = "0.0.0"
description = "Dummy file for Codex bootstrap"
requires-python = ">=3.12"

[build-system]
requires = []
build-backend = "uv"
